GET http://localhost:8080/currecencyExchanger_war_exploded/

###

GET http://localhost:8080/currecencyExchanger_war_exploded/currencies

###

GET http://localhost:8080/currecencyExchanger_war_exploded/currency/UAH

###

GET http://localhost:8080/currecencyExchanger_war_exploded/exchangeRates

###

GET http://localhost:8080/currecencyExchanger_war_exploded/exchangeRate/USDUAH

###

GET http://localhost:8080/currecencyExchanger_war_exploded/exchangeRate/USDKZT

###

POST http://localhost:8080/currecencyExchanger_war_exploded/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrency = USD &
targetCurrency = EUR &
rate = 0.96

###

POST http://localhost:8080/currecencyExchanger_war_exploded/currencies
Content-Type: application/x-www-form-urlencoded

name = Euro &
code = EUR &
sign = €




