GET http://localhost:8080/currecencyExchanger_war_exploded/

###

GET http://localhost:8080/currecencyExchanger_war_exploded/currencies

###

GET http://localhost:8080/currecencyExchanger_war_exploded/currency/UAH

###

GET http://localhost:8080/currecencyExchanger_war_exploded/exchangeRates

###

GET http://localhost:8080/currecencyExchanger_war_exploded/exchangeRate/USDUAH

###

GET http://localhost:8080/currecencyExchanger_war_exploded/exchangeRate/USDKZT

###

POST http://localhost:8080/currecencyExchanger_war_exploded/exchangeRates
Content-Type: application/x-www-form-urlencoded

baseCurrencyCode = USD &
targetCurrencyCode = UAH &
rate = 37.93

###

POST http://localhost:8080/currecencyExchanger_war_exploded/currencies
Content-Type: application/x-www-form-urlencoded

name = Zlotyi &
code = PLN &
sign = zł

###

PATCH http://localhost:8080/currecencyExchanger_war_exploded/exchangeRate/USDUAH
Content-Type: application/x-www-form-urlencoded

rate = 37.93




